-- Loading dataset
CREATE DATABASE NETFLIX_DB;
USE NETFLIX_DB;
CREATE TABLE NETFLIX_TITLES (
SHOW_ID VARCHAR(20),
`TYPE` VARCHAR(10),
TITLE VARCHAR(255),
DIRECTOR VARCHAR(255),
`CAST` TEXT,
COUNTRY VARCHAR(500),
DATE_ADDED VARCHAR(50),
RELEASE_YEAR INT,
RATING VARCHAR(10),
DURATION VARCHAR(50),
LISTED_IN TEXT,
`DESCRIPTION` TEXT);

SHOW VARIABLES LIKE 'SECURE_FILE_PRIV';


LOAD DATA INFILE "C:/ProgramData/MySQL/MySQL Server 9.2/Uploads/netflix_titles.csv"
INTO TABLE NETFLIX_TITLES
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM netflix_titles;

-- DATA HANDLING
UPDATE netflix_titles SET DIRECTOR = NULL WHERE DIRECTOR ='';
UPDATE netflix_titles SET COUNTRY = NULL WHERE COUNTRY ='';
UPDATE netflix_titles SET `cast` = NULL WHERE `Cast` ='';

ALTER TABLE NETFLIX_TITLES
ADD COLUMN DATE_ADDED_CLEAN DATE;

UPDATE netflix_titles SET date_added = NULL WHERE date_added ='';
UPDATE NETFLIX_TITLES
SET DATE_ADDED_CLEAN = str_to_date(DATE_ADDED, '%M %d,%Y')
where date_added IS NOT NULL;

-- SQL FINDINGS

-- 1. TOTAL COUNT OF MOVIES AND TV SHOWS
SELECT `TYPE`,COUNT(*) AS TOTAL_COUNT FROM NETFLIX_TITLES
GROUP BY `TYPE`;

-- 2. TOP 3 MOST CONTENT PRODUCING COUNTRY
SELECT COUNTRY, COUNT(*) AS TOTAL_CONTENT
FROM NETFLIX_TITLES
GROUP BY COUNTRY
HAVING COUNTRY IS NOT NULL
ORDER BY TOTAL_CONTENT DESC
LIMIT 3;

-- 3. THE OLDEST AND NEWEST TITLE AVAILABLE ON NETFLIX
SELECT TITLE, RELEASE_YEAR AS OLDEST_YEAR
FROM NETFLIX_TITLES
ORDER BY RELEASE_YEAR ASC 
LIMIT 1;

SELECT TITLE, RELEASE_YEAR AS NEWEST_YEAR
FROM NETFLIX_TITLES
ORDER BY RELEASE_YEAR DESC
LIMIT 1;

-- 4. THE YEAR IN WHICH MOST SHOWS/MOVIES GET ADDED TO NETFLIX
SELECT YEAR(DATE_ADDED_CLEAN), COUNT(*) AS TOTAL_CONTENT
FROM NETFLIX_TITLES
GROUP BY YEAR(DATE_ADDED_CLEAN)
ORDER BY TOTAL_CONTENT DESC
LIMIT 1;

-- 5. MOST COMMON CONTENT RATINGS
SELECT RATING, COUNT(*) AS TOTAL 
FROM NETFLIX_TITLES
GROUP BY RATING
ORDER BY TOTAL DESC
LIMIT 1;

-- 6. TOP 5 LONGEST MOVIES BY MINUTES AND TV SHOWS BY SEASONS
SELECT TITLE ,DURATION
FROM NETFLIX_TITLES
WHERE `TYPE`="MOVIE"
ORDER BY CAST(SUBSTRING_INDEX(DURATION, ' ',1) AS unsigned) DESC
LIMIT 5;

SELECT TITLE ,DURATION
FROM NETFLIX_TITLES
WHERE `TYPE`="TV SHOW"
ORDER BY CAST(SUBSTRING_INDEX(DURATION, ' ',1) AS unsigned) DESC
LIMIT 5;

-- 7. COUNTRIES THAT HAVE BOTH MOVIES AND TV SHOWS
SELECT COUNTRY
FROM NETFLIX_TITLES
WHERE COUNTRY IS NOT NULL
GROUP BY COUNTRY
HAVING COUNT(distinct`TYPE`)= 2;

-- 8. MOST COMMON GENRES
SELECT LISTED_IN, COUNT(*)
FROM NETFLIX_TITLES
GROUP BY LISTED_IN
ORDER BY COUNT(*) DESC
LIMIT 3;

-- 9. ACTORS APPEARS MOST FREQUENT
SELECT `CAST`, COUNT(*)
FROM NETFLIX_TITLES
GROUP BY `CAST`
HAVING `CAST` IS NOT NULL
ORDER BY COUNT(*) DESC
LIMIT 5;

-- 10. MOST FREQUENT DIRECTORS
SELECT DIRECTOR, COUNT(*)
FROM NETFLIX_TITLES
GROUP BY DIRECTOR
HAVING DIRECTOR IS NOT NULL
ORDER BY COUNT(*) DESC
LIMIT 5;

-- 11. CATEGORIZE MOVIE COUNT BASED ON DURATION
SELECT TITLE, DURATION,
CASE
WHEN CAST(SUBSTRING_INDEX(DURATION, ' ',1) AS unsigned) <60 THEN "SHORT_MOVIE"
WHEN CAST(SUBSTRING_INDEX(DURATION, ' ',1) AS unsigned) BETWEEN 60 AND 120 THEN "MEDIUM_MOVIE"
ELSE "LONG_MOVIE"
END AS MOVIE_CATEGORY
FROM NETFLIX_TITLES
WHERE `TYPE` = "MOVIE";

-- 12. CATEGORIZE MOVIE THEME
 SELECT TITLE, 
 CASE
 WHEN `DESCRIPTION` LIKE "%LOVE%" OR `DESCRIPTION` LIKE "%ROMANTIC%" OR `DESCRIPTION` LIKE "%RELATIONSHIP%" THEN "LOVE"
 WHEN `DESCRIPTION` LIKE "%GHOST%" OR `DESCRIPTION` LIKE "%HORROR%" OR `DESCRIPTION` LIKE "%HAUNTED%" THEN "HORROR"
 WHEN `DESCRIPTION` LIKE "%FIGHT%" OR `DESCRIPTION` LIKE "%BATTLE%" OR `DESCRIPTION` LIKE "%WAR%" THEN "ACTION"
 WHEN `DESCRIPTION` LIKE "%FUNNY%" OR `DESCRIPTION` LIKE "%LAUGH%" OR `DESCRIPTION` LIKE "%COMEDY%" THEN "COMEDY"
 WHEN `DESCRIPTION` LIKE "%MYSTERY%" OR `DESCRIPTION` LIKE "%CRIME%" OR `DESCRIPTION` LIKE "%MURDER%" THEN "SUSPENCE"
 ELSE "OTHER"
 END AS MOVIE_THEME
 FROM NETFLIX_TITLES;


 




